"""empty message

Revision ID: 3d153f202d54
Revises: 4ee01b321ebc
Create Date: 2021-10-01 20:50:51.643467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d153f202d54'
down_revision = '4ee01b321ebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_comments', sa.Column('event_id111', sa.Integer(), nullable=False))
    op.drop_constraint('event_comments_event_id_fkey', 'event_comments', type_='foreignkey')
    op.create_foreign_key(None, 'event_comments', 'events', ['event_id111'], ['id'])
    op.drop_column('event_comments', 'event_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_comments', sa.Column('event_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_comments', type_='foreignkey')
    op.create_foreign_key('event_comments_event_id_fkey', 'event_comments', 'events', ['event_id'], ['id'])
    op.drop_column('event_comments', 'event_id111')
    # ### end Alembic commands ###
