"""empty message

Revision ID: 4a140b9e05e5
Revises: 6798d91481b2
Create Date: 2021-10-03 19:35:05.338768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4a140b9e05e5'
down_revision = '6798d91481b2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_comments', sa.Column('event_id', sa.Integer(), nullable=False))
    op.drop_constraint('event_comments_event_id111_fkey', 'event_comments', type_='foreignkey')
    op.create_foreign_key(None, 'event_comments', 'events', ['event_id'], ['id'])
    op.drop_column('event_comments', 'event_id111')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_comments', sa.Column('event_id111', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'event_comments', type_='foreignkey')
    op.create_foreign_key('event_comments_event_id111_fkey', 'event_comments', 'events', ['event_id111'], ['id'])
    op.drop_column('event_comments', 'event_id')
    # ### end Alembic commands ###
