"""empty message

Revision ID: 54abe74b8732
Revises: 59b824cc11ad
Create Date: 2021-10-01 16:57:03.423856

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '54abe74b8732'
down_revision = '59b824cc11ad'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('avatar_url2', sa.String(length=400), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'avatar_url2')
    # ### end Alembic commands ###
