"""empty message

Revision ID: 6798d91481b2
Revises: 3d153f202d54
Create Date: 2021-10-01 20:55:58.602404

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6798d91481b2'
down_revision = '3d153f202d54'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('event_comments', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'event_comments', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'event_comments', type_='foreignkey')
    op.drop_column('event_comments', 'user_id')
    # ### end Alembic commands ###
